/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import { TaaviSkeptic as TaaviSkeptic } from './components/taavi-skeptic/taavi-skeptic';

interface HTMLTaaviSkepticElement extends TaaviSkeptic, HTMLElement {
}
declare var HTMLTaaviSkepticElement: {
  prototype: HTMLTaaviSkepticElement;
  new (): HTMLTaaviSkepticElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "taavi-skeptic": HTMLTaaviSkepticElement;
  }
  interface ElementTagNameMap {
      "taavi-skeptic": HTMLTaaviSkepticElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "taavi-skeptic": JSXElements.TaaviSkepticAttributes;
      }
  }
  namespace JSXElements {
      export interface TaaviSkepticAttributes extends HTMLAttributes {
          mode?: string,
          color?: string,
        
          first?: string,
          last?: string
      }
  }
}

